# Generated by Django 4.2.4 on 2023-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_size1_alter_product_size2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size5',
        ),
    ]
